name: Continuous Delivery

on:
    push:
        branches: [ "main" ]
        paths:
          - 'parsoda/**'
          - 'test/**'
          - 'resources/input/**'
          - 'Dockerfile'
          - 'requirements**'
          - '.github/workflows/continuous-delivery.yml'
    pull_request:
        branches: [ "main" ]
        paths:
          - 'parsoda/**'
          - 'test/**'
          - 'resources/input/**'
          - 'Dockerfile'
          - 'requirements**'
          - '.github/workflows/continuous-delivery.yml'

permissions:
  contents: read

jobs:
    docker-build-push:
        runs-on: ubuntu-latest
        steps:
        - 
            name: Create current version based on time
            id: versioning
            run: |
                echo "::set-output name=version::$(date +'%Y%m%d-%H%M%S' --utc)"
        - 
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        - 
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        - 
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        - 
            name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                tags: ${{secrets.DOCKER_USERNAME}}/parsoda:latest, ${{secrets.DOCKER_USERNAME}}/parsoda:${{steps.versioning.outputs.version}}
                
