# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    #runs-on: ubuntu-latest
    container:
      image: compss/compss:latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Install PyCOMPSs
    #   run: |
    #     # installs software dependencies through APT package manager
    #     sudo apt install -y software-properties-common wget
    #     sudo apt install -y zip openjdk-8-jdk graphviz xdg-utils libtool automake build-essential python python-dev libpython2.7 libboost-serialization-dev libboost-iostreams-dev libxml2 libxml2-dev csh gfortran libgmp3-dev flex bison texinfo libpapi-dev
    #     sudo apt install -y python3 python3-dev python3-pip
        
    #     # downloads and installs gradle
    #     wget https://services.gradle.org/distributions/gradle-5.4.1-bin.zip -O /opt/gradle-5.4.1-bin.zip
    #     unzip /opt/gradle-5.4.1-bin.zip -d /opt
        
    #     # exports environment variables
    #     echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/' >> ~/.bashrc
    #     export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
    #     echo 'export GRADLE_HOME=/opt/gradle-5.4.1' >> ~/.bashrc
    #     export GRADLE_HOME=/opt/gradle-5.4.1
    #     echo 'export PATH=/opt/gradle-5.4.1/bin:$PATH' >> ~/.bashrc
    #     export PATH=/opt/gradle-5.4.1/bin:$PATH
        
    #     # upgrade pip and setuptools
    #     python3 -m pip install --upgrade pip setuptools
        
    #     # installs library dependencies for PyCOMPSs
    #     python3 -m pip install dill guppy3
        
    #     # installs the latest version of PyCOMPSs
    #     python3 -m pip install pycompss -v
    - name: Install PySpark
      run: |
        python3 -m pip install pyspark
    - name: Test with unittest
      run: |
        python3 -m unittest -v
